export const REQUEST_GET_ONE_FILE_SUCCESS = 'REQUEST_GET_ONE_FILE_SUCCESS';
export const REQUEST_GET_FILE_SUCCESS = 'REQUEST_GET_FILE_SUCCESS';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ATTACHMENT_SUCCESS = 'REQUEST_ATTACHMENT_SUCCESS';

//
export const REQUEST_ADD_STUDENT_SUCCESS = 'REQUEST_ADD_STUDENT_SUCCESS'
export const REQUEST_GET_STUDENT_SUCCESS = 'REQUEST_GET_STUDENT_SUCCESS'
export const REQUEST_GET_ONE_STUDENT_SUCCESS = 'REQUEST_GET_ONE_STUDENT_SUCCESS'